# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4623490351da7366e9e6d619df0b3cd76e93940808dbfd05983b137fd2052d98b4e2a07c475f677a3fde423a11ecc002a3c3ad224b7b4df06656b0c59aa8a4fb

test:
  secret_key_base: 29b564ab977f196c4f89b1d23fd998a4d61a8c4ca76d08f6e526e828d71ce6b8b77ffd5e9ea2d8e9a5e00b46a9697767d34b677e51400be759d113d2cb641a8e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
